### ISSUE TITLE
Define a branch for the environment variable

### ISSUE THREAD

**Issue by marth154** [dkershner6/vercel-set-env-action#148]
I was looking through the vercel docs and saw that you could set an environment variable on a particular branch, which is pretty handy and I think it would be useful

**Comment by dkershner6** [comment]
"branch" isn't exactly how it works, but there are three separate targets for environment variables in Vercel, and you control them like so:

> TARGET_ENV_VAR1: production # comma delimited, one of [production, preview, development]

In the above case, it will only apply to production, but the value `production,preview,deployment` would apply to all.

This is admittedly not a perfect interface, but GitHub actions doesn't play very well with arrays and objects.
