### ISSUE TITLE
Not considering gitBranch for existingEnvVariables

### ISSUE THREAD

**Issue by wagnertimo** [dkershner6/vercel-set-env-action#166]
Hey @dkershner6 thanks for this GH action!

### Problem and expected behavior
There are some issues regarding Preview Environment Variables with different git branch names. 
If you want to use the "same" preview env var (e.g. `DB_URL`) for several git branches (e.g. `foo` and `bar`), then the first declared preview env var of a git branch (e.g. `foo`) will get wrongly updated (in that case overwritten/"deleted") by the preview env var of another git branch (e.g. `bar`) declared afterwards. 
It should be expected, that the first preview env var (`DB_URL` for branch `foo`) is still present along new preview env vars ( e.g. `DB_URL` for branch `bar`) when set later.

### Cause and hint to a solution
This is due to a not distinguishable enough check of the `existingEnvVariables` in the `processEnvVariable` function ([see here](https://github.com/dkershner6/vercel-set-env-action/blob/main/src/VercelEnvVariabler.ts#L97-L107)). There, only the `target` (`Development`, `Preview` and `Production`) and `envVariableKey` (e.g. `DB_URL`) are considered. **But not additionally** the optional `gitBranch` values (e.g. `foo` and `bar`). 
Hence, every new git branch declaration (e.g. `bar`) for the preview env var e.g. `DB_URL`, will patch the "previous" env var and thereby "delete" them. The "previous", because the env var id of the existing variable (`existingVariable.id`) is taken from the first element `Object.values(existingVariables)[0]` to be patched (instead of creating a new env var). 
You literally state in a comment `// They are all actually the same` which they are obviously not when considering also `gitBranch` 😅  ([see here](https://github.com/dkershner6/vercel-set-env-action/blob/main/src/VercelEnvVariabler.ts#L240))

**Comment by dkershner6** [comment]
This should now be present in the marketplace, thank you for your contribution.
