### ISSUE TITLE
Github actions deprecation warning

### ISSUE THREAD

**Issue by freeversity** [dkershner6/vercel-set-env-action#169]
Hey!

First of all, thanks for the lib! It saved me a lot of headeache.

Currently I get this message in my workflow pipeline:

`The following actions uses node12 which is deprecated and will be forced to run on node16: dkershner6/vercel-set-env-action@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`

Would it be possible to update the node version?

**Comment by dkershner6** [comment]
This is now released (node 18) under the tag v2 (you will need to update your workflow, this is just in case something goes awry, but I doubt it will).
